ldap:
  HOST                 : ldap://192.168.1.247:389
  VERSION              : 3
  SSL                  : False
  TIMEOUT              : 30
  BIND_DN              : cn=xxx,ou=xxx,dc=xxx,dc=com
  BIND_PASS            : xxxxxx
  BASE_DN              : dc=xxx,dc=com
  USERS_DN             : ou=Users,dc=xxxxxx,dc=com
  USERS_FILTER         : (uid=%u)
  #  USERS_SEARCH_SCOPE   : LDAP_SCOPE_ONELEVEL
#   USER_SEARCH_SCOPE    : LDAP_SCOPE_BASE 、LDAP_SCOPE_ONELEVEL 、LDAP_SCOPE_SUBTREE
  GROUP_DN             : ou=OpenVPN,ou=Groups,dc=xxxxxx,dc=com
  GROUP_FILTER         : (|(objectclass=groupOfNames)(objectclass=groupOfUniqueNames)(objectclass=posixGroup))
  GROUP_MEMBER_ATTR    : uniqueMember
#  GROUP_FIELD          : cn,description
#   TLS_CACERTFILE       : xxxx
#   TLS_CACERTDIR        : xxxx
#   TLS_CERTFILE         : xxxx
#   TLS_CERTKEY          : xxxx
#   TLS_CIPHERSUITE      : xxxx
#   TLS_REQCERT          : xxxx
#  GROUP_FIELD  定义根据组名定义 iptable 的链名
  GROUP_MAP_FIELD      : 
    - cn
#    - description
  ENABLE_LDAP_IPTABLE  : True
  IPTABLE_RULES_FIELD  : iptableRoles

    
# 策略定义 源IP不用添加，系统自动添加
iptablerules:
  vpn-admin: '-p all -j ACCEPT'
  vpn-development: 
      - '-p tcp -m tcp -d 172.18.207.240/32 --dport 3306 -j ACCEPT'
  vpn-developadmin:
      - '-p tcp -m tcp -d 172.18.207.0/24 -m multiport --dports 80,443,3306,6379,8500 -j ACCEPT'
  vpn-common:
      - '-p tcp -m tcp -d 172.18.51.120/32 -m multiport --dports 80,443,22 -j ACCEPT'
  vpn-test:
      - '-p tcp -m tcp -d 172.18.207.240/32 --dport 3306 -j ACCEPT'
