FROM alpine as skywalking
ENV PATH=$PATH:/opt/jdk/bin \
    JAVA_HOME=/opt/jdk/ \
    SKYWALKING_VERSION=8.9.1   

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && cd /opt \
    && funwget() { wget -c -t 0 $1 -O - |tar -zxf -; if [ $? -ne 0 ]; then echo $1;funwget $1; fi } \
    && funwget https://dlcdn.apache.org/skywalking/${SKYWALKING_VERSION}/apache-skywalking-apm-${SKYWALKING_VERSION}.tar.gz \
    && mv apache-skywalking* skywalking 

FROM anapsix/alpine-java:latest
ARG  SKYWALKING_PREFIX=/a/apps/skywalking
MAINTAINER dbh888 <duanbaihong@qq.com>

ENV PATH=$PATH:/opt/jdk/bin \
    JAVA_HOME=/opt/jdk/ \
    SKYWALKING_PREFIX=${SKYWALKING_PREFIX}/ \
    JAVA_OPTS="" \
    SKYWALKING_ARGS="" \
    PS1='[\u@\w]$'

WORKDIR $SKYWALKING_PREFIX

COPY --from=skywalking /opt/skywalking  $SKYWALKING_PREFIX/

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add bash dumb-init \
    && rm -rf $SKYWALKING_PREFIX/oap-libs \
    $SKYWALKING_PREFIX/tools \
    $SKYWALKING_PREFIX/licenses \
    $SKYWALKING_PREFIX/config-examples \
    $SKYWALKING_PREFIX/agent \
    $SKYWALKING_PREFIX/LICENSE \
    $SKYWALKING_PREFIX/NOTICE \
    $SKYWALKING_PREFIX/README.txt

ADD entrypoint-skywalking-ui.sh /bin/

EXPOSE 8080

ENTRYPOINT [ "/bin/entrypoint-skywalking-ui.sh" ]